# function available minimum required
availableFunctions:
  - plotVarDemo
integratedFunctions:
# web client integrated function configuration
  plotVarDemo:
    description : > 
      \### Compare two variables \n
      A demo app that help you to compare two variables
    label: "Compare two variables"
    type: graphic
    graphicType: plotly
    formParameters:
      varURI:
        label: "Variables"
        type: list
        maxSelectedItem: 2
        RfunctionValues: variableList
        required: true
      token:
        type: string
        visibility: hidden
        required: true
      wsUrl:
        type: string
        visibility: hidden
        required: true